spring:
  application:
    name: course-catalog-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
      # h2 DB console - http://localhost:8080/h2-console
#   url: jdbc:postgrese:
message: Hello from default profile

# Instead of all the profiles being defined here
#    it is better to create separate files named as 'application-prod.yml' 'application-dev.yml'
#  Which profile [prod; dev] is controlled by the runtime VM option -Dspring.profiles.active=prod
#
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#message: Hello from 'prod' profile
#
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#message: Hello from 'dev' profile

