spring:
  application:
    name: course-catalog-service
  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/courses
    username: postgres
    password: postgres
  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop #this recreates the db, not recommended for prod
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: true
      # h2 DB console - http://localhost:8080/h2-console
#   url: jdbc:postgrese:
message: Hello from default profile



# Instead of all the profiles being defined here
#    it is better to create separate files named as 'application-prod.yml' 'application-dev.yml'
#  Which profile [prod; dev] is controlled by the runtime VM option -Dspring.profiles.active=prod
#
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#message: Hello from 'prod' profile
#
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#message: Hello from 'dev' profile

