package org.swamy.coursecatalogservice.entity

import jakarta.persistence.*

@Entity
@Table(name ="Courses")
data class Course (

    @Id // to indicate that this is the primary key, that will be auto generated by DB
    @GeneratedValue(strategy = GenerationType.AUTO)
    val id: Int?, //Defined as a Nullable since this will be DB generated

    var name: String,
    var category : String
)