package org.swamy.coursecatalogservice.entity

import jakarta.persistence.*

@Entity
@Table(name = "INSTRUCTORS")
data class Instructor(
    @Id // to indicate that this is the primary key, that will be auto generated by DB
    @GeneratedValue(strategy = GenerationType.AUTO)
    val id: Int?, //Defined as a Nullable since this will be DB generated

    var name: String,

    @OneToMany(
        mappedBy = "instructor",
        cascade = [CascadeType.ALL],
        orphanRemoval = true
    )
    var courses : List<Course> = mutableListOf()
)
